-- ops-core MySQL schema — import via phpMyAdmin (Database > SQL tab > paste > Go).
-- Generated by scripts/export_schema.py. The running app also applies these
-- automatically at boot; importing by hand is optional.
-- Table prefix: 'opscore_'

-- ===== 001_init.sql =====
-- ops-core initial schema — MySQL / MariaDB (InnoDB, utf8mb4).
-- Applied automatically by app/db.py at boot, and also importable directly into
-- phpMyAdmin (see deploy/schema.mysql.sql for a prefix-applied copy).
--
-- Timestamps are stored as UTC ISO-8601 strings in CHAR(25) (e.g.
-- "2026-08-05T09:30:00+00:00"). Fixed width => lexicographic order == chronological,
-- so every `due_at <= now` comparison in the timer logic stays a plain string compare
-- and Rule 4 (UTC in storage, IST at the edges) holds without timezone-typed columns.
--
-- Deviations from the design doc's section 5 schema (all additive/minimal; see README):
--   * opscore_incidents.resolve_due_at  -- grace-window timer as a ROW (Rule 1), false-restart guard.
--   * opscore_escalations.ticket_id is NULLABLE and opscore_escalations.incident_id + opscore_escalations.action
--     were added so the pre-ticket "unknown"/ask_reason ladder can run against an incident.
--   * opscore_inbound_raw.matched_incident_id -- a Phase-1 reply answers a reason prompt on an incident.
--   * `condition` and `trigger` are reserved words in MySQL, kept as column names via backticks.

-- Every CREATE is IF NOT EXISTS so this file is RE-RUNNABLE. MySQL implicitly commits
-- each DDL statement, so a migration cannot be atomic: if one fails partway (or the
-- tables were imported by hand via phpMyAdmin), the opscore_schema_migrations row never gets
-- written and the next boot would re-run the file. Without IF NOT EXISTS that boot dies
-- on "Table 'opscore_assets' already exists" and the deployment is stuck with no way forward
-- short of dropping tables by hand.

CREATE TABLE IF NOT EXISTS opscore_assets (
  id          VARCHAR(128) NOT NULL,            -- "weaving:loom_23"
  department  VARCHAR(64)  NOT NULL,
  asset_ref   VARCHAR(64)  NOT NULL,            -- "loom_23"
  label       VARCHAR(255) NULL,
  active      TINYINT      NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_asset (department, asset_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_incidents (
  id             BIGINT       NOT NULL AUTO_INCREMENT,
  asset_id       VARCHAR(128) NOT NULL,
  department     VARCHAR(64)  NOT NULL,
  opened_at      CHAR(25)     NOT NULL,         -- UTC ISO8601
  resolved_at    CHAR(25)     NULL,
  duration_s     INT          NULL,             -- computed on resolve
  shift          VARCHAR(8)   NULL,             -- A / B / C, resolved at open
  `condition`    VARCHAR(128) NULL,             -- from the source
  status         VARCHAR(16)  NOT NULL,         -- open | resolving | resolved
  resolve_due_at CHAR(25)     NULL,             -- grace-window timer (false-restart guard)
  PRIMARY KEY (id),
  KEY ix_inc_open  (status, department),
  KEY ix_inc_asset (asset_id, opened_at),
  CONSTRAINT fk_inc_asset FOREIGN KEY (asset_id) REFERENCES opscore_assets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_incident_reasons (
  id          BIGINT      NOT NULL AUTO_INCREMENT,
  incident_id BIGINT      NOT NULL,
  code        VARCHAR(64) NOT NULL,             -- "weaving.electrical"
  subcode     VARCHAR(64) NULL,                 -- "float", "khonk"
  method      VARCHAR(16) NOT NULL,             -- panel | reply | auto | backfill
  actor       VARCHAR(64) NULL,                 -- person id, or "system"
  at          CHAR(25)    NOT NULL,
  PRIMARY KEY (id),
  KEY ix_reason_incident (incident_id),
  CONSTRAINT fk_reason_inc FOREIGN KEY (incident_id) REFERENCES opscore_incidents(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_tickets (
  id                BIGINT      NOT NULL AUTO_INCREMENT,
  incident_id       BIGINT      NOT NULL,
  department        VARCHAR(64) NOT NULL,
  code              VARCHAR(64) NOT NULL,
  owner_role        VARCHAR(64) NOT NULL,
  opened_at         CHAR(25)    NOT NULL,
  first_notified_at CHAR(25)    NULL,
  attended_at       CHAR(25)    NULL,           -- presence at the asset (Phase 2; NULL in Phase 1)
  attended_by       VARCHAR(64) NULL,
  diagnosis         VARCHAR(255) NULL,          -- optional, from the fitter
  closed_at         CHAR(25)    NULL,
  close_reason      VARCHAR(32) NULL,           -- asset_resumed | manual | stale
  reopen_count      INT         NOT NULL DEFAULT 0,
  status            VARCHAR(16) NOT NULL,       -- open | attended | closed
  PRIMARY KEY (id),
  KEY ix_tkt_open      (status, department),
  KEY ix_tkt_incident  (incident_id),
  CONSTRAINT fk_tkt_inc FOREIGN KEY (incident_id) REFERENCES opscore_incidents(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_escalations (
  id           BIGINT      NOT NULL AUTO_INCREMENT,
  ticket_id    BIGINT      NULL,                -- set once a ticket exists
  incident_id  BIGINT      NULL,                -- set for the pre-ticket "unknown" ladder
  rung         INT         NOT NULL,
  notify_role  VARCHAR(64) NOT NULL,
  action       VARCHAR(32) NULL,                -- ask_reason | notify (NULL == notify)
  due_at       CHAR(25)    NOT NULL,            -- the timer, persisted
  fired_at     CHAR(25)    NULL,
  status       VARCHAR(16) NOT NULL,            -- pending | fired | cancelled
  `trigger`    VARCHAR(16) NULL,                -- timer | recurrence
  PRIMARY KEY (id),
  KEY ix_esc_due (status, due_at),
  CONSTRAINT fk_esc_tkt FOREIGN KEY (ticket_id)   REFERENCES opscore_tickets(id),
  CONSTRAINT fk_esc_inc FOREIGN KEY (incident_id) REFERENCES opscore_incidents(id),
  CONSTRAINT chk_esc_parent CHECK (ticket_id IS NOT NULL OR incident_id IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_outbox (
  id              BIGINT       NOT NULL AUTO_INCREMENT,
  channel         VARCHAR(16)  NOT NULL,        -- whatsapp | gchat | panel | log
  recipient       VARCHAR(191) NOT NULL,
  payload         JSON         NOT NULL,
  dedupe_key      VARCHAR(191) NOT NULL,
  attempts        INT          NOT NULL DEFAULT 0,
  next_try_at     CHAR(25)     NOT NULL,
  sent_at         CHAR(25)     NULL,
  provider_msg_id VARCHAR(128) NULL,
  status          VARCHAR(16)  NOT NULL,        -- queued | sent | failed
  PRIMARY KEY (id),
  UNIQUE KEY uq_dedupe (dedupe_key),
  KEY ix_out_due (status, next_try_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_inbound_raw (
  id                  BIGINT      NOT NULL AUTO_INCREMENT,
  channel             VARCHAR(16) NOT NULL,
  received_at         CHAR(25)    NOT NULL,
  body                TEXT        NOT NULL,      -- verbatim, before parsing
  matched_ticket_id   BIGINT      NULL,
  matched_incident_id BIGINT      NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS opscore_events (                            -- append-only, never updated, never deleted
  id         BIGINT      NOT NULL AUTO_INCREMENT,
  at         CHAR(25)    NOT NULL,
  department VARCHAR(64) NULL,
  entity     VARCHAR(16) NOT NULL,               -- incident | ticket | escalation
  entity_id  BIGINT      NOT NULL,
  kind       VARCHAR(24) NOT NULL,               -- opened | reason_set | notified | escalated | ...
  actor      VARCHAR(64) NULL,                   -- person id or "system"
  detail     JSON        NULL,
  PRIMARY KEY (id),
  KEY ix_ev_entity (entity, entity_id),
  KEY ix_ev_at     (at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== 002_inbound_sender.sql =====
-- Record WHO sent an inbound message, not just what they sent.
--
-- WhatsApp bills business-initiated template messages but delivers free-form replies
-- free inside the 24-hour "customer service window" that opens whenever the person
-- messages us. To use that window we have to know, per recipient, when they last wrote
-- to us — which the original opscore_inbound_raw could not answer, since it stored only the
-- verbatim body.
--
-- It matters for correctness as much as cost: outside the window ONLY an approved
-- template may be sent, so a notifier that cannot tell which side of the window it is
-- on will eventually try to send free text and be rejected by Meta.
--
-- Stored as digits only (no '+', no spaces) because Meta reports `from` as
-- "919000000001" while routing.yaml carries "+91 90000 00001". Normalising on the way
-- in means the lookup never has to guess at a format.

ALTER TABLE opscore_inbound_raw ADD COLUMN sender VARCHAR(64) NULL;
ALTER TABLE opscore_inbound_raw ADD INDEX ix_inbound_sender (channel, sender, received_at);

-- ===== 003_config_overrides.sql =====
-- Runtime-editable configuration.
--
-- The YAML files stay the base: git-tracked, heavily commented, and the thing you read
-- to understand the system. This table holds the DELTA applied on top, written by the
-- config API at runtime.
--
-- Why an overlay rather than rewriting the YAML in place:
--   * A YAML round-trip destroys comments, and the comments in reasons.yaml and
--     source.yaml are load-bearing documentation — why the RPM threshold is 40, why
--     fleet_fraction is 1.0 at four looms. Machine-writing those files would silently
--     delete the reasoning behind every number.
--   * Reverting a bad 3am edit becomes DELETE of one row, not a git operation on a
--     server.
--   * State that must survive a restart already lives in MySQL. Config is now the same
--     kind of thing as a pending timer.
--
-- One row per scope, holding the whole merged document as JSON. Effective config is
-- the YAML with this applied as an RFC 7386 merge patch, validated as a unit before
-- it is ever committed — so the boot-time "fail loud" guarantee becomes "reject the
-- write", never "accept a config that routes nothing to nobody".

CREATE TABLE IF NOT EXISTS opscore_config_overrides (
  scope      VARCHAR(32) NOT NULL,          -- reasons | routing | escalation
  patch      MEDIUMTEXT  NOT NULL,          -- JSON merge patch over the YAML
  updated_at CHAR(25)    NOT NULL,
  updated_by VARCHAR(64) NULL,
  PRIMARY KEY (scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===== bookkeeping =====
CREATE TABLE IF NOT EXISTS opscore_schema_migrations (
  name VARCHAR(191) NOT NULL,
  applied_at CHAR(25) NOT NULL,
  PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO opscore_schema_migrations(name, applied_at)
  VALUES ('001_init.sql', DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%S+00:00'));
INSERT IGNORE INTO opscore_schema_migrations(name, applied_at)
  VALUES ('002_inbound_sender.sql', DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%S+00:00'));
INSERT IGNORE INTO opscore_schema_migrations(name, applied_at)
  VALUES ('003_config_overrides.sql', DATE_FORMAT(UTC_TIMESTAMP(), '%Y-%m-%dT%H:%i:%S+00:00'));
