"""Emit deploy/schema.mysql.sql — the MySQL DDL, ready to paste into the phpMyAdmin SQL
tab. Applies OPS_TABLE_PREFIX (default none) so the exported file matches how the app
will name its tables. Regenerate after changing the prefix or adding a migration.

Run: python -m scripts.export_schema
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from app.db import _TABLES, _TABLE_RE  # noqa: E402  (import after dotenv)

ROOT = Path(__file__).resolve().parent.parent
prefix = os.environ.get("OPS_TABLE_PREFIX", "")


def main():
    parts = [
        "-- ops-core MySQL schema — import via phpMyAdmin (Database > SQL tab > paste > Go).",
        "-- Generated by scripts/export_schema.py. The running app also applies these",
        "-- automatically at boot; importing by hand is optional.",
        f"-- Table prefix: {'(none)' if not prefix else repr(prefix)}",
        "",
    ]
    for path in sorted((ROOT / "migrations").glob("*.sql")):
        sql = path.read_text(encoding="utf-8")
        if prefix:
            for t in _TABLES:
                sql = _TABLE_RE[t].sub(prefix + t, sql)
        parts.append(f"-- ===== {path.name} =====")
        parts.append(sql.rstrip())
        parts.append("")
    out = ROOT / "deploy" / "schema.mysql.sql"
    out.write_text("\n".join(parts), encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
